# .github/workflows/update-custom-domain.yml
name: Update Custom Domain

on:
    push:
        branches:
            - main # or the branch you use for GitHub Pages

jobs:
    update-domain:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Update custom domain
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  CUSTOM_DOMAIN: mohsinriaz.ca # replace with your domain
              run: |
                  curl -X PATCH \
                    -H "Accept: application/vnd.github.v3+json" \
                    -H "Authorization: token $GITHUB_TOKEN" \
                    -d "{\"cname\":\"$CUSTOM_DOMAIN\"}" \
                    "https://api.github.com/repos/${{ github.repository }}/pages"
